// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD6qHzCtMum3GRSkF328be6p0Ak9Mdiv0',
    appId: '1:665570350872:web:898364551d9d8e111af06d',
    messagingSenderId: '665570350872',
    projectId: 'todo-5049d',
    authDomain: 'todo-5049d.firebaseapp.com',
    storageBucket: 'todo-5049d.appspot.com',
    measurementId: 'G-QWHWPRD5VF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYvg8kXrYoXbRlbk7HXab_qWaUJBh4HxI',
    appId: '1:665570350872:android:078d78e744c7c7431af06d',
    messagingSenderId: '665570350872',
    projectId: 'todo-5049d',
    storageBucket: 'todo-5049d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxMLAuiSMjuXWG8vUYiPihUKT-0SUAyw',
    appId: '1:665570350872:ios:1083d3ba5c7a78411af06d',
    messagingSenderId: '665570350872',
    projectId: 'todo-5049d',
    storageBucket: 'todo-5049d.appspot.com',
    iosClientId: '665570350872-v4o4ba4kmcnumd5h07j83fb27npu9n86.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatplan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxMLAuiSMjuXWG8vUYiPihUKT-0SUAyw',
    appId: '1:665570350872:ios:1904776c3dc6fd3a1af06d',
    messagingSenderId: '665570350872',
    projectId: 'todo-5049d',
    storageBucket: 'todo-5049d.appspot.com',
    iosClientId: '665570350872-901tbhqfiptsdgccfqhgpvhvaedh6bft.apps.googleusercontent.com',
    iosBundleId: 'com.example.creatplan.RunnerTests',
  );
}
